# Generated by Django 5.0.4 on 2024-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('telefone', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id_vendas', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('produto', models.TextField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.TextField(max_length=50)),
            ],
        ),
    ]
